# Generated by Django 4.2.13 on 2026-07-18 14:29
"""
Replaces the freeform, unvalidated `desired_job_type` CharField with a
structured `desired_job_types` JSONField (list of Job.JOB_TYPE_CHOICES
codes -- e.g. ['full_time', 'contract']). The old field was never actually
wired into any serializer, view, or frontend form (confirmed by search
across the codebase before this migration was written), so no data
migration is needed -- there was nothing populating it to preserve.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='desired_job_type',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='desired_job_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
