# Generated by Django 4.2.13 on 2026-07-24 21:26
"""
Adds company_role (owner/admin/member/viewer) to RecruiterProfile.
Resolves the flat-team-permission gap: previously every teammate had
identical access with no way to have a read-only recruiter or to revoke a
bad-actor's access short of them leaving voluntarily. The accompanying data
migration backfills OWNER for whoever created each existing Company and
MEMBER for everyone else already on one, so no existing team member
silently loses access when this ships (a blank role would already default
to full access per RecruiterProfile.can_manage_jobs, but explicit is safer
than relying on that fallback long-term).
"""

from django.db import migrations, models


def backfill_company_roles(apps, schema_editor):
    RecruiterProfile = apps.get_model('accounts', 'RecruiterProfile')
    for profile in RecruiterProfile.objects.filter(company__isnull=False, company_role=''):
        is_owner = profile.company.created_by_id == profile.user_id
        profile.company_role = 'owner' if is_owner else 'member'
        profile.save(update_fields=['company_role'])


def noop_reverse(apps, schema_editor):
    pass  # nothing to reverse -- blank company_role is itself a safe, valid state


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_team_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=10),
        ),
        migrations.RunPython(backfill_company_roles, noop_reverse),
    ]
