# Generated by Django 4.2.13 on 2026-07-31 09:36
"""
Adds CandidateProfile.visibility (actively_looking/open_to_offers/not_visible),
a more expressive successor to the plain open_to_work boolean. Both fields
are kept going forward -- open_to_work stays the field every existing query
filters on, visibility is the newer field surfaced in the UI and synced
from it at the API layer (see CandidateProfileUpdateSerializer).

The AddField default (open_to_offers) is correct for anyone who currently
has open_to_work=True, but WRONG for anyone who already set
open_to_work=False -- they opted out, and should land on not_visible, not
silently become visible again. The data migration below corrects exactly
that group.
"""

from django.db import migrations, models


def backfill_visibility_for_opted_out_candidates(apps, schema_editor):
    CandidateProfile = apps.get_model('accounts', 'CandidateProfile')
    CandidateProfile.objects.filter(open_to_work=False).update(visibility='not_visible')


def noop_reverse(apps, schema_editor):
    pass  # nothing to reverse -- the default value is itself a valid state


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recruiterprofile_company_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='visibility',
            field=models.CharField(choices=[('actively_looking', 'Actively looking'), ('open_to_offers', 'Open to offers'), ('not_visible', 'Not visible to recruiters')], default='open_to_offers', max_length=20),
        ),
        migrations.RunPython(backfill_visibility_for_opted_out_candidates, noop_reverse),
    ]
