# Generated by Django 4.2.13 on 2026-09-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_candidateprofile_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='visibility',
        ),
    ]
