"""
python manage.py seed_jobs

Seeds 108 diverse jobs across 14 companies covering:
  Tech · Data · Healthcare · Finance · Education · Gaming · Clean Energy
  Retail · Hospitality · Legal · Architecture · Media · Logistics · Charity

All job types: full_time, part_time, contract, freelance, internship
All work modes: onsite, remote, hybrid
All experience levels: entry, mid, senior, lead, executive

Run with --clear to wipe existing seed data first.
"""
from django.core.management.base import BaseCommand
from django.db import transaction

RECRUITERS = [
    # 0 — Tech
    {'email': 'testrecruiter@gmail.com', 'full_name': 'Test Recruiter', 'password': 'BytesJobs#26',
     'company': {'company_name': 'TechCorp Solutions', 'company_description': 'Leading software consultancy for enterprise clients.', 'industry': 'Software / Technology', 'company_size': '201-1000', 'location': 'London, UK', 'company_website': 'https://techcorp.example.com'}},
    # 1 — Data
    {'email': 'talent@dataventures.io', 'full_name': 'James Okafor', 'password': 'BytesJobs#26',
     'company': {'company_name': 'DataVentures', 'company_description': 'Data-first startup helping companies make smarter decisions with AI.', 'industry': 'Data & Analytics', 'company_size': '11-50', 'location': 'Manchester, UK', 'company_website': 'https://dataventures.example.io'}},
    # 2 — Healthcare
    {'email': 'careers@healthtechuk.com', 'full_name': 'Amira Hassan', 'password': 'BytesJobs#26',
     'company': {'company_name': 'HealthTech UK', 'company_description': 'Building the future of NHS-integrated digital healthcare.', 'industry': 'Healthcare Technology', 'company_size': '51-200', 'location': 'Birmingham, UK', 'company_website': 'https://healthtechuk.example.com'}},
    # 3 — Finance
    {'email': 'jobs@financehub.co.uk', 'full_name': 'Marcus Webb', 'password': 'BytesJobs#26',
     'company': {'company_name': 'FinanceHub', 'company_description': 'Fintech scale-up modernising financial infrastructure.', 'industry': 'Fintech / Banking', 'company_size': '51-200', 'location': 'London, UK', 'company_website': 'https://financehub.example.co.uk'}},
    # 4 — Creative
    {'email': 'hello@creativeagency.co.uk', 'full_name': 'Priya Nair', 'password': 'BytesJobs#26',
     'company': {'company_name': 'CreativeAgency', 'company_description': 'Award-winning creative studio specialising in brand, digital, and content.', 'industry': 'Design & Marketing', 'company_size': '11-50', 'location': 'Bristol, UK', 'company_website': 'https://creativeagency.example.co.uk'}},
    # 5 — EdTech
    {'email': 'jobs@learnpath.co.uk', 'full_name': 'Emma Davies', 'password': 'BytesJobs#26',
     'company': {'company_name': 'LearnPath', 'company_description': 'EdTech platform making quality education accessible through AI-powered learning.', 'industry': 'Education Technology', 'company_size': '51-200', 'location': 'Cambridge, UK', 'company_website': 'https://learnpath.example.co.uk'}},
    # 6 — Gaming
    {'email': 'careers@pixelforge.games', 'full_name': 'Jake Thompson', 'password': 'BytesJobs#26',
     'company': {'company_name': 'PixelForge Studios', 'company_description': 'Independent game studio creating innovative mobile and PC games.', 'industry': 'Gaming', 'company_size': '11-50', 'location': 'Guildford, UK', 'company_website': 'https://pixelforge.example.games'}},
    # 7 — Clean Energy
    {'email': 'talent@ecosystems.green', 'full_name': 'Sophie Green', 'password': 'BytesJobs#26',
     'company': {'company_name': 'EcoSystems', 'company_description': 'Clean energy tech for renewable grid management and sustainability reporting.', 'industry': 'Clean Energy & Sustainability', 'company_size': '51-200', 'location': 'Edinburgh, UK', 'company_website': 'https://ecosystems.example.green'}},
    # 8 — Retail
    {'email': 'people@shopnow.co.uk', 'full_name': 'Rachel Turner', 'password': 'BytesJobs#26',
     'company': {'company_name': 'ShopNow Retail', 'company_description': 'UK omnichannel retailer with 200+ stores and a growing e-commerce platform.', 'industry': 'Retail & E-commerce', 'company_size': '1001-5000', 'location': 'Leeds, UK', 'company_website': 'https://shopnow.example.co.uk'}},
    # 9 — Hospitality
    {'email': 'hr@grandhotels.co.uk', 'full_name': 'Thomas Carter', 'password': 'BytesJobs#26',
     'company': {'company_name': 'Grand Hotels Group', 'company_description': 'Luxury hotel group operating 15 properties across the UK and Ireland.', 'industry': 'Hospitality & Tourism', 'company_size': '1001-5000', 'location': 'London, UK', 'company_website': 'https://grandhotels.example.co.uk'}},
    # 10 — Legal
    {'email': 'recruitment@lawbridge.co.uk', 'full_name': 'Caroline Hughes', 'password': 'BytesJobs#26',
     'company': {'company_name': 'LawBridge LLP', 'company_description': 'Full-service commercial law firm with offices in London, Manchester, and Edinburgh.', 'industry': 'Legal Services', 'company_size': '201-1000', 'location': 'London, UK', 'company_website': 'https://lawbridge.example.co.uk'}},
    # 11 — Architecture
    {'email': 'jobs@designspace.co.uk', 'full_name': 'Oliver Chan', 'password': 'BytesJobs#26',
     'company': {'company_name': 'DesignSpace Architects', 'company_description': 'Award-winning architecture and urban design practice specialising in sustainable buildings.', 'industry': 'Architecture & Construction', 'company_size': '51-200', 'location': 'London, UK', 'company_website': 'https://designspace.example.co.uk'}},
    # 12 — Media
    {'email': 'talent@northstarmedia.co.uk', 'full_name': 'Hannah Price', 'password': 'BytesJobs#26',
     'company': {'company_name': 'NorthStar Media', 'company_description': 'Independent media company producing documentaries, podcasts, and digital journalism.', 'industry': 'Media & Journalism', 'company_size': '11-50', 'location': 'Glasgow, UK', 'company_website': 'https://northstar.example.co.uk'}},
    # 13 — Charity
    {'email': 'hr@hopefoundation.org.uk', 'full_name': 'Diana Osei', 'password': 'BytesJobs#26',
     'company': {'company_name': 'Hope Foundation', 'company_description': 'UK charity supporting young people with mental health challenges through community programmes.', 'industry': 'Charity & Non-profit', 'company_size': '51-200', 'location': 'London, UK', 'company_website': 'https://hopefoundation.example.org.uk'}},
]

CANDIDATES = [
    {'email': 'alex.chen@email.com', 'full_name': 'Alex Chen', 'password': 'BytesJobs#26',
     'profile': {'headline': 'Full-Stack Developer | React & Django', 'bio': '5 years building web applications. Passionate about clean APIs and great UX.', 'location': 'London, UK', 'skills': ['Python', 'Django', 'React', 'TypeScript', 'PostgreSQL', 'Docker', 'REST APIs', 'Git'], 'experience_years': 5, 'open_to_work': True}},
    {'email': 'testcandidate@gmail.com', 'full_name': 'Test Candidate', 'password': 'BytesJobs#26',
     'profile': {'headline': 'Data Scientist | ML & NLP Specialist', 'bio': 'MSc Data Science. Expert in NLP, scikit-learn, turning messy data into insights.', 'location': 'Edinburgh, UK', 'skills': ['Python', 'Machine Learning', 'NLP', 'scikit-learn', 'TensorFlow', 'SQL', 'Pandas', 'Tableau'], 'experience_years': 3, 'open_to_work': True}},
    {'email': 'tom.walker@email.com', 'full_name': 'Tom Walker', 'password': 'BytesJobs#26',
     'profile': {'headline': 'DevOps Engineer | AWS & Kubernetes', 'bio': '4 years automating infrastructure. AWS Certified Solutions Architect.', 'location': 'Bristol, UK', 'skills': ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'CI/CD', 'Python', 'Linux', 'Jenkins'], 'experience_years': 4, 'open_to_work': True}},
]

JOBS = [
    # ── TECHCORP (0) ─────────────────────────────────────────────────────────
    {'title': 'Senior Full-Stack Developer', 'description': 'Lead feature development across our React frontend and Django REST backend for enterprise clients.', 'requirements': '4+ years full-stack · React/TypeScript · Python/Django · PostgreSQL', 'responsibilities': 'Design and implement features end-to-end · Review PRs · Mentor juniors', 'skills_required': ['React', 'TypeScript', 'Python', 'Django', 'PostgreSQL', 'Docker'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 70000, 'salary_max': 90000, 'category': 'Software Engineering', 'company_idx': 0},
    {'title': 'React Frontend Engineer', 'description': 'Own the UI of our flagship SaaS product. React 18, TypeScript, Tailwind CSS, React Query.', 'requirements': '2+ years React · TypeScript · WCAG accessibility knowledge', 'responsibilities': 'Build component library · Implement responsive features · Optimise Core Web Vitals', 'skills_required': ['React', 'TypeScript', 'Tailwind CSS', 'JavaScript', 'CSS'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote (UK)', 'salary_min': 55000, 'salary_max': 70000, 'category': 'Software Engineering', 'company_idx': 0},
    {'title': 'Backend Python Developer', 'description': 'Build the Django REST API powering our platform. Own services, write tests, shape architecture.', 'requirements': '3+ years Python · Django REST Framework · PostgreSQL · Redis', 'responsibilities': 'Design REST APIs · Optimise queries · Write tests', 'skills_required': ['Python', 'Django', 'PostgreSQL', 'Redis', 'Celery', 'REST APIs'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 60000, 'salary_max': 75000, 'category': 'Software Engineering', 'company_idx': 0},
    {'title': 'Junior Software Engineer (Graduate)', 'description': 'Kick-start your career with mentoring, pair programming, and real feature work from week one.', 'requirements': 'CS degree · Programming fundamentals · Python or JavaScript', 'responsibilities': 'Contribute features under mentorship · Write unit tests · Participate in code review', 'skills_required': ['Python', 'JavaScript', 'Git', 'REST APIs'], 'job_type': 'full_time', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 32000, 'salary_max': 42000, 'category': 'Software Engineering', 'company_idx': 0},
    {'title': 'DevOps / Platform Engineer', 'description': 'Own AWS cloud infrastructure. Build Kubernetes clusters, CI/CD pipelines, and observability tooling.', 'requirements': '3+ years DevOps · AWS EKS/RDS/S3 · Kubernetes · Terraform', 'responsibilities': 'Scale Kubernetes · Build CI/CD · Manage cloud costs', 'skills_required': ['AWS', 'Kubernetes', 'Terraform', 'Docker', 'CI/CD', 'Linux'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 75000, 'salary_max': 95000, 'category': 'DevOps & Infrastructure', 'company_idx': 0},
    {'title': 'iOS Developer (Swift)', 'description': 'Build our native iOS app used by 200,000+ users. UI animations, push notifications, offline sync.', 'requirements': '2+ years iOS/Swift · SwiftUI · UIKit · MVVM', 'responsibilities': 'Ship iOS features · Write UI tests · Collaborate with backend', 'skills_required': ['Swift', 'SwiftUI', 'UIKit', 'iOS', 'Xcode', 'Core Data'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 60000, 'salary_max': 78000, 'category': 'Mobile Development', 'company_idx': 0},
    {'title': 'Freelance React Developer', 'description': 'Short-term freelance (2–3 months) to build a client-facing dashboard. Fully remote, weekly billing.', 'requirements': 'Strong React/TypeScript · Chart.js or Recharts · Available 4+ days/week', 'responsibilities': 'Build dashboard components · Integrate REST API · Handover docs', 'skills_required': ['React', 'TypeScript', 'JavaScript', 'CSS', 'REST APIs'], 'job_type': 'freelance', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote', 'salary_min': 400, 'salary_max': 550, 'category': 'Software Engineering', 'company_idx': 0},
    {'title': 'Principal Engineer', 'description': 'Shape technical strategy for our entire engineering org. Set standards, drive best practices, solve the hardest problems.', 'requirements': '10+ years engineering · Architecture experience · Influencing culture', 'responsibilities': 'Set engineering standards · Lead architecture reviews · Mentor staff engineers', 'skills_required': ['System Design', 'Architecture', 'Leadership', 'Python', 'Cloud', 'Mentoring'], 'job_type': 'full_time', 'experience_level': 'executive', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 120000, 'salary_max': 150000, 'category': 'Software Engineering', 'company_idx': 0},
    {'title': 'Software Engineering Intern (Summer)', 'description': '12-week paid internship for penultimate-year students. Real features, senior mentor, end-of-programme showcase.', 'requirements': 'Studying CS · Some coding experience (any language) · Curious and communicative', 'responsibilities': 'Build a defined feature · Write tests · Present at intern showcase', 'skills_required': ['Python', 'JavaScript', 'Git'], 'job_type': 'internship', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 22000, 'salary_max': 26000, 'category': 'Software Engineering', 'company_idx': 0},
    # ── DATAVENTURES (1) ─────────────────────────────────────────────────────
    {'title': 'Data Scientist', 'description': 'Build ML models that predict customer behaviour, detect anomalies, and optimise pricing for enterprise clients.', 'requirements': 'MSc/PhD in Data Science or 3+ years · Python · SQL · NLP', 'responsibilities': 'Build ML models · Clean datasets · Present to clients', 'skills_required': ['Python', 'Machine Learning', 'scikit-learn', 'SQL', 'Pandas', 'NLP'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Manchester, UK', 'salary_min': 55000, 'salary_max': 72000, 'category': 'Data Science', 'company_idx': 1},
    {'title': 'Machine Learning Engineer', 'description': 'Deploy models at scale, build feature pipelines, maintain ML infrastructure for enterprise clients.', 'requirements': '2+ years deploying ML in production · Python · MLflow · Docker/Kubernetes', 'responsibilities': 'Productionise models · Build pipelines · Monitor drift', 'skills_required': ['Python', 'Machine Learning', 'Docker', 'MLflow', 'scikit-learn', 'TensorFlow'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote (UK)', 'salary_min': 65000, 'salary_max': 85000, 'category': 'Data Science', 'company_idx': 1},
    {'title': 'NLP Research Engineer', 'description': 'Fine-tune LLMs, build information extraction pipelines, advance NLP capabilities for enterprise clients.', 'requirements': 'PhD or strong MSc in NLP · HuggingFace Transformers · PyTorch', 'responsibilities': 'Fine-tune language models · Build NLP pipelines · Publish research notes', 'skills_required': ['NLP', 'Python', 'PyTorch', 'HuggingFace', 'Transformers', 'Machine Learning'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'hybrid', 'location': 'Manchester, UK', 'salary_min': 80000, 'salary_max': 105000, 'category': 'Data Science', 'company_idx': 1},
    {'title': 'Data Science Intern (6 months)', 'description': 'Structured internship with a real project alongside senior data scientists.', 'requirements': 'Studying CS/Maths/Statistics · Python experience · Basic stats', 'responsibilities': 'Explore datasets · Build simple ML models · Present weekly', 'skills_required': ['Python', 'Statistics', 'Pandas', 'Machine Learning'], 'job_type': 'internship', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'Manchester, UK', 'salary_min': 22000, 'salary_max': 26000, 'category': 'Data Science', 'company_idx': 1},
    {'title': 'Freelance Data Analyst', 'description': 'Flexible engagements 2 weeks–3 months. Client data analysis, insights reports, and presentations.', 'requirements': 'Strong SQL and Python or R · Data visualisation · Independent worker', 'responsibilities': 'Analyse client datasets · Produce insight reports · Present findings', 'skills_required': ['SQL', 'Python', 'Data Visualisation', 'Excel', 'Tableau'], 'job_type': 'freelance', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote', 'salary_min': 300, 'salary_max': 450, 'category': 'Data Science', 'company_idx': 1},
    # ── HEALTHTECH UK (2) ────────────────────────────────────────────────────
    {'title': 'Healthcare Software Engineer', 'description': 'Build NHS-integrated software improving patient outcomes. Clinical decision support, appointment systems, data pipelines.', 'requirements': '2+ years software engineering · HL7 FHIR a plus · GDPR awareness', 'responsibilities': 'Develop NHS features · Ensure GDPR compliance · Write clinical APIs', 'skills_required': ['Python', 'Django', 'HL7 FHIR', 'PostgreSQL', 'REST APIs', 'GDPR'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Birmingham, UK', 'salary_min': 52000, 'salary_max': 68000, 'category': 'Healthcare Technology', 'company_idx': 2},
    {'title': 'Medical Imaging AI Engineer', 'description': 'Develop AI for X-ray, MRI, and pathology slide interpretation. Work with clinicians to validate outputs.', 'requirements': 'MSc/PhD in ML or Computer Vision · PyTorch · Medical imaging libraries', 'responsibilities': 'Train and validate imaging models · Collaborate with clinical partners · Write validation reports', 'skills_required': ['PyTorch', 'Computer Vision', 'Python', 'Medical Imaging', 'Deep Learning', 'CNN'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'remote', 'location': 'Remote (UK)', 'salary_min': 75000, 'salary_max': 95000, 'category': 'Healthcare Technology', 'company_idx': 2},
    {'title': 'Clinical Data Analyst', 'description': 'Analyse clinical datasets to improve patient care pathways. Work with NHS trusts and GPs.', 'requirements': 'Health informatics/statistics background · SQL and Python or R · NHS data experience preferred', 'responsibilities': 'Analyse clinical data · Produce insight reports · Identify care pathway improvements', 'skills_required': ['SQL', 'Python', 'R', 'Health Informatics', 'Data Visualisation', 'SNOMED CT'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Birmingham, UK', 'salary_min': 42000, 'salary_max': 55000, 'category': 'Healthcare Technology', 'company_idx': 2},
    {'title': 'NHS Digital Consultant (Contract)', 'description': '6-month contract leading an NHS digital transformation programme. Stakeholder management, delivery oversight.', 'requirements': 'NHS digital project experience · Agile delivery · Stakeholder management · SC clearance eligible', 'responsibilities': 'Lead NHS digital workstreams · Manage stakeholders · Report to board sponsors', 'skills_required': ['NHS', 'Digital Transformation', 'Stakeholder Management', 'Agile', 'Project Management'], 'job_type': 'contract', 'experience_level': 'senior', 'work_mode': 'hybrid', 'location': 'Birmingham, UK', 'salary_min': 500, 'salary_max': 650, 'category': 'Healthcare Technology', 'company_idx': 2},
    {'title': 'Digital Health Intern', 'description': '3-month internship for students interested in the intersection of technology and healthcare.', 'requirements': 'Studying healthcare, CS, or related · Interest in digital health · Basic coding', 'responsibilities': 'Support feature development · Research digital health trends · Present to team', 'skills_required': ['Python', 'Research', 'Healthcare', 'Communication'], 'job_type': 'internship', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'Birmingham, UK', 'salary_min': 20000, 'salary_max': 24000, 'category': 'Healthcare Technology', 'company_idx': 2},
    # ── FINANCEHUB (3) ───────────────────────────────────────────────────────
    {'title': 'Quantitative Developer', 'description': 'Build quantitative systems powering risk and pricing models alongside senior quants.', 'requirements': 'Strong Python/C++ · Financial mathematics · Low-latency systems a plus', 'responsibilities': 'Implement quant models · Optimise pricing performance · Write comprehensive tests', 'skills_required': ['Python', 'C++', 'NumPy', 'Finance', 'Risk Modelling', 'Low Latency'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 90000, 'salary_max': 130000, 'category': 'Finance & Fintech', 'company_idx': 3},
    {'title': 'Payment Systems Engineer', 'description': 'Build payment gateway and reconciliation systems processing millions of transactions. PSD2 compliance required.', 'requirements': '3+ years backend · Payment processing (Stripe/Adyen) · PSD2 awareness', 'responsibilities': 'Build payment gateway integrations · Maintain reconciliation pipelines · Ensure PSD2 compliance', 'skills_required': ['Python', 'Stripe', 'PSD2', 'Payments', 'PostgreSQL', 'REST APIs'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 65000, 'salary_max': 82000, 'category': 'Finance & Fintech', 'company_idx': 3},
    {'title': 'Blockchain Developer', 'description': 'Build on Ethereum and Solana for DeFi products and smart contract infrastructure.', 'requirements': 'Solidity · Web3.js/ethers.js · DeFi protocols knowledge · Audit mindset', 'responsibilities': 'Write and audit smart contracts · Build Web3 integrations · Stay current with DeFi', 'skills_required': ['Solidity', 'Ethereum', 'Web3.js', 'Blockchain', 'Smart Contracts', 'DeFi'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'remote', 'location': 'Remote (UK)', 'salary_min': 85000, 'salary_max': 110000, 'category': 'Finance & Fintech', 'company_idx': 3},
    {'title': 'Finance Intern — Technology', 'description': '10-week summer internship in our technology division. Real fintech challenges alongside engineers and quants.', 'requirements': 'Studying CS/Maths/Finance/Engineering · Analytical mindset · Excel or Python', 'responsibilities': 'Support technology projects · Analyse financial data · Present to stakeholders', 'skills_required': ['Python', 'Excel', 'Finance', 'Analysis'], 'job_type': 'internship', 'experience_level': 'entry', 'work_mode': 'onsite', 'location': 'London, UK', 'salary_min': 24000, 'salary_max': 28000, 'category': 'Finance & Fintech', 'company_idx': 3},
    {'title': 'Freelance Compliance Consultant', 'description': 'FCA regulation expertise and compliance framework reviews. 2–4 week projects, flexible remote.', 'requirements': 'Deep FCA knowledge · Compliance assessment experience · Strong writing · FCA registered', 'responsibilities': 'Review compliance frameworks · Produce regulatory gap analyses · Advise on FCA requirements', 'skills_required': ['FCA Regulation', 'Compliance', 'Financial Services', 'Risk Management', 'Reporting'], 'job_type': 'freelance', 'experience_level': 'senior', 'work_mode': 'remote', 'location': 'Remote', 'salary_min': 500, 'salary_max': 750, 'category': 'Finance & Fintech', 'company_idx': 3},
    # ── CREATIVE AGENCY (4) ──────────────────────────────────────────────────
    {'title': 'Senior UX Designer', 'description': 'Lead design on biggest client accounts. From research and wireframes to high-fidelity Figma prototypes.', 'requirements': '5+ years UX design · Figma component libraries · User research · Accessibility', 'responsibilities': 'Lead design for key accounts · Run usability testing · Mentor junior designers', 'skills_required': ['Figma', 'UX Research', 'Prototyping', 'Design Systems', 'User Testing', 'Accessibility'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'hybrid', 'location': 'Bristol, UK', 'salary_min': 60000, 'salary_max': 78000, 'category': 'Design & UX', 'company_idx': 4},
    {'title': 'Brand Designer', 'description': 'Shape visual identities of startups and scale-ups. Logo, colour, typography, brand guidelines.', 'requirements': 'Strong brand portfolio · Figma and Adobe Creative Suite · Client communication', 'responsibilities': 'Lead brand identity projects · Present to clients · Produce brand guidelines', 'skills_required': ['Brand Design', 'Figma', 'Adobe Illustrator', 'Adobe Photoshop', 'Typography', 'Motion'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Bristol, UK', 'salary_min': 42000, 'salary_max': 56000, 'category': 'Design & UX', 'company_idx': 4},
    {'title': 'Freelance Motion Designer', 'description': 'Social media content, explainer videos, brand campaigns. Project-based, fully remote.', 'requirements': 'Strong After Effects · Social video formats · Portfolio of motion work · Fast turnaround', 'responsibilities': 'Create motion graphics · Animate brand assets · Deliver project files', 'skills_required': ['After Effects', 'Motion Design', 'Premier Pro', 'Figma', 'Animation', 'Social Media'], 'job_type': 'freelance', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote', 'salary_min': 300, 'salary_max': 500, 'category': 'Design & UX', 'company_idx': 4},
    {'title': 'Content Marketing Manager', 'description': 'Build and execute content strategy driving organic growth. Own blog, social, case studies, newsletter.', 'requirements': '3+ years content marketing · Strong writing · SEO · Content calendar management', 'responsibilities': 'Own content strategy · Write blog posts and case studies · Manage social presence', 'skills_required': ['Content Marketing', 'SEO', 'Copywriting', 'Social Media', 'Analytics', 'HubSpot'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Bristol, UK', 'salary_min': 38000, 'salary_max': 50000, 'category': 'Marketing', 'company_idx': 4},
    {'title': 'Creative Director', 'description': 'Lead creative vision of CreativeAgency. Inspire designers and writers, win pitches, ensure outstanding work.', 'requirements': '10+ years creative industry · Leading creative teams · Strong client and presentation skills', 'responsibilities': 'Lead creative direction · Win pitches · Mentor creative team', 'skills_required': ['Creative Direction', 'Brand Strategy', 'Leadership', 'Presentation', 'Design', 'Copywriting'], 'job_type': 'full_time', 'experience_level': 'executive', 'work_mode': 'onsite', 'location': 'Bristol, UK', 'salary_min': 90000, 'salary_max': 120000, 'category': 'Design & UX', 'company_idx': 4},
    # ── LEARNPATH (5) ────────────────────────────────────────────────────────
    {'title': 'Senior Software Engineer (EdTech)', 'description': 'Build core learning platform used by 500,000 students. Adaptive learning, video streaming, real-time collaboration.', 'requirements': '4+ years software engineering · Python or Node.js · Video/streaming tech · PostgreSQL', 'responsibilities': 'Lead platform feature development · Optimise video delivery · Mentor engineers', 'skills_required': ['Python', 'Node.js', 'React', 'PostgreSQL', 'Redis', 'AWS'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'remote', 'location': 'Remote (UK)', 'salary_min': 72000, 'salary_max': 92000, 'category': 'Software Engineering', 'company_idx': 5},
    {'title': 'AI / ML Engineer — Personalised Learning', 'description': 'Build AI engine personalising each student learning path using RL, knowledge graphs, and NLP.', 'requirements': 'Strong ML background · Recommendation systems · Python and PyTorch', 'responsibilities': 'Build adaptive learning algorithm · Analyse student performance · A/B test recommendations', 'skills_required': ['Python', 'Machine Learning', 'Recommendation Systems', 'NLP', 'PyTorch', 'Knowledge Graphs'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'remote', 'location': 'Remote (UK)', 'salary_min': 78000, 'salary_max': 98000, 'category': 'Data Science', 'company_idx': 5},
    {'title': 'Learning Experience Designer', 'description': 'Design evidence-based online courses and assessments with subject matter experts.', 'requirements': 'Instructional design experience · E-learning tools (Articulate, H5P) · Learning science', 'responsibilities': 'Design course structures · Collaborate with subject experts · Evaluate learning outcomes', 'skills_required': ['Instructional Design', 'E-learning', 'H5P', 'Curriculum Design', 'Assessment'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Cambridge, UK', 'salary_min': 38000, 'salary_max': 50000, 'category': 'Education Technology', 'company_idx': 5},
    {'title': 'Freelance Curriculum Developer (Mathematics)', 'description': 'Create A-Level and university Maths content. Flexible, paid per module, fully remote.', 'requirements': 'Maths degree · Teaching or curriculum development · LaTeX knowledge', 'responsibilities': 'Write course content and exercises · Create assessment materials · Review peer content', 'skills_required': ['Mathematics', 'Curriculum Development', 'LaTeX', 'Education', 'Content Writing'], 'job_type': 'freelance', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote', 'salary_min': 200, 'salary_max': 400, 'category': 'Education Technology', 'company_idx': 5},
    {'title': 'EdTech Intern — Software Engineering', 'description': 'Summer internship for CS students building things students use every day.', 'requirements': 'Studying CS or Software Engineering · Some programming experience · Interest in education', 'responsibilities': 'Build a defined feature · Write tests · Demo your work at the end', 'skills_required': ['Python', 'JavaScript', 'Git', 'React'], 'job_type': 'internship', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'Cambridge, UK', 'salary_min': 21000, 'salary_max': 25000, 'category': 'Software Engineering', 'company_idx': 5},
    # ── PIXELFORGE (6) ───────────────────────────────────────────────────────
    {'title': 'Unity Game Developer', 'description': 'Build gameplay systems for mobile and PC titles in a small, fast-moving studio.', 'requirements': '2+ years Unity development · C# · Shipped a commercial game · Mobile performance', 'responsibilities': 'Implement core gameplay · Optimise for iOS/Android · Collaborate with artists', 'skills_required': ['Unity', 'C#', 'Mobile', 'Game Development', 'Performance Optimisation', 'iOS', 'Android'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'onsite', 'location': 'Guildford, UK', 'salary_min': 48000, 'salary_max': 65000, 'category': 'Gaming', 'company_idx': 6},
    {'title': 'Senior Game Designer', 'description': 'Own design of upcoming PC title. Systems, progression loops, and level designs for hundreds of hours of play.', 'requirements': '4+ years game design · Shipped game in portfolio · Systems design · Player psychology', 'responsibilities': 'Write game design documents · Design and balance progression · Playtest and iterate', 'skills_required': ['Game Design', 'Systems Design', 'Level Design', 'GDD', 'Unity', 'Player Psychology'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'onsite', 'location': 'Guildford, UK', 'salary_min': 58000, 'salary_max': 76000, 'category': 'Gaming', 'company_idx': 6},
    {'title': 'Freelance Concept Artist', 'description': 'Character, environment, and UI concepts for upcoming title. Project-based, remote-friendly.', 'requirements': 'Strong concept art portfolio (games preferred) · Photoshop or Procreate · Fast iteration', 'responsibilities': 'Create character and environment concepts · Iterate on feedback · Produce style guide assets', 'skills_required': ['Concept Art', 'Photoshop', 'Procreate', 'Character Design', 'Environment Art'], 'job_type': 'freelance', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote', 'salary_min': 350, 'salary_max': 550, 'category': 'Gaming', 'company_idx': 6},
    {'title': 'Community Manager (Games)', 'description': 'Build and nurture player community across Discord, Reddit, Twitter/X, and Steam.', 'requirements': 'Community management experience · Deep games passion · Strong writing · Discord communities', 'responsibilities': 'Manage Discord and social · Run community events · Relay player feedback', 'skills_required': ['Community Management', 'Discord', 'Social Media', 'Gaming', 'Copywriting', 'Player Relations'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote (UK)', 'salary_min': 32000, 'salary_max': 44000, 'category': 'Marketing', 'company_idx': 6},
    # ── ECOSYSTEMS (7) ───────────────────────────────────────────────────────
    {'title': 'Software Engineer — Energy Grid', 'description': 'Build software managing renewable energy distribution across the UK grid. Real-time data, optimisation algorithms.', 'requirements': 'Software engineering background · Python or Java · Real-time/IoT systems a plus', 'responsibilities': 'Build grid management APIs · Process energy telemetry · Integrate with grid operators', 'skills_required': ['Python', 'Java', 'Real-time Systems', 'IoT', 'PostgreSQL', 'REST APIs'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Edinburgh, UK', 'salary_min': 55000, 'salary_max': 72000, 'category': 'Software Engineering', 'company_idx': 7},
    {'title': 'Sustainability Analyst', 'description': 'Produce carbon reporting and ESG analytics for corporate clients. Help companies measure and reduce carbon footprint.', 'requirements': 'Environmental science/engineering/data background · GHG Protocol · SQL and Python', 'responsibilities': 'Produce carbon emissions reports · Advise on decarbonisation · Build ESG dashboards', 'skills_required': ['Carbon Accounting', 'ESG', 'GHG Protocol', 'Python', 'Data Analysis', 'Excel'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Edinburgh, UK', 'salary_min': 42000, 'salary_max': 56000, 'category': 'Sustainability', 'company_idx': 7},
    {'title': 'Renewable Energy Graduate Scheme', 'description': '2-year rotational scheme covering software engineering, data science, and sustainability consulting.', 'requirements': 'STEM degree · Genuine passion for climate · Some coding experience · Adaptable', 'responsibilities': 'Rotate across software, data, and consulting · Contribute to live projects · Present to leadership', 'skills_required': ['Python', 'Data Analysis', 'Sustainability', 'Communication', 'Adaptability'], 'job_type': 'full_time', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'Edinburgh, UK', 'salary_min': 30000, 'salary_max': 36000, 'category': 'Sustainability', 'company_idx': 7},
    {'title': 'Carbon Software Analyst (Part-time)', 'description': 'Support corporate clients using our carbon management platform. 3 days per week.', 'requirements': 'Environmental or data background · Carbon accounting knowledge · Excel · Good communication', 'responsibilities': 'Help clients set up carbon tracking · Produce monthly reports · Train users', 'skills_required': ['Carbon Accounting', 'Excel', 'Sustainability', 'Client Support', 'Data Entry'], 'job_type': 'part_time', 'experience_level': 'entry', 'work_mode': 'remote', 'location': 'Remote (UK)', 'salary_min': 24000, 'salary_max': 32000, 'category': 'Sustainability', 'company_idx': 7},
    # ── SHOPNOW RETAIL (8) ───────────────────────────────────────────────────
    {'title': 'E-commerce Trading Manager', 'description': 'Drive online sales performance across our 200+ product categories. Own trading calendar, promotional campaigns, and pricing strategy for our e-commerce platform.', 'requirements': '3+ years e-commerce trading · Strong analytical skills · Excel and Google Analytics · Retail background', 'responsibilities': 'Own trading calendar and promotions · Analyse conversion and basket data · Collaborate with buying and marketing', 'skills_required': ['E-commerce', 'Trading', 'Google Analytics', 'Excel', 'Retail', 'CMS Management'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Leeds, UK', 'salary_min': 40000, 'salary_max': 54000, 'category': 'Retail & E-commerce', 'company_idx': 8},
    {'title': 'Retail Store Manager', 'description': 'Lead a high-performing store team of 25 in our flagship Leeds location. Own all aspects of store operations, sales, and colleague development.', 'requirements': '3+ years retail management · Experience leading teams · P&L awareness · Customer-first mindset', 'responsibilities': 'Lead and develop store team · Drive sales targets · Manage stock and operations', 'skills_required': ['Retail Management', 'Team Leadership', 'P&L', 'Customer Service', 'Stock Management'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'onsite', 'location': 'Leeds, UK', 'salary_min': 32000, 'salary_max': 42000, 'category': 'Retail & E-commerce', 'company_idx': 8},
    {'title': 'Supply Chain Analyst', 'description': 'Optimise our supply chain and logistics network across 200 stores. Demand forecasting, supplier management, inventory planning.', 'requirements': '2+ years supply chain or logistics · SQL and Excel · Demand forecasting experience · FMCG or retail background', 'responsibilities': 'Analyse supply chain performance · Run demand forecasts · Work with suppliers on lead times', 'skills_required': ['Supply Chain', 'Demand Forecasting', 'SQL', 'Excel', 'Logistics', 'ERP Systems'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Leeds, UK', 'salary_min': 35000, 'salary_max': 46000, 'category': 'Retail & E-commerce', 'company_idx': 8},
    {'title': 'Digital Marketing Executive', 'description': 'Execute digital marketing campaigns across paid social, SEO, and email to drive online and in-store traffic.', 'requirements': '1+ year digital marketing · Social ads (Meta, Google) · Email marketing platforms · Basic analytics', 'responsibilities': 'Run paid social and search campaigns · Manage email newsletters · Report on campaign performance', 'skills_required': ['Digital Marketing', 'Facebook Ads', 'Google Ads', 'Email Marketing', 'Analytics', 'SEO'], 'job_type': 'full_time', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'Leeds, UK', 'salary_min': 26000, 'salary_max': 34000, 'category': 'Marketing', 'company_idx': 8},
    {'title': 'Part-time Sales Assistant', 'description': 'Deliver exceptional customer service on the shop floor. Weekend and evening availability required.', 'requirements': 'Customer service experience · Friendly and reliable · Weekend availability · Team player', 'responsibilities': 'Assist customers · Process transactions · Maintain shop floor presentation', 'skills_required': ['Customer Service', 'Retail', 'Cash Handling', 'Communication', 'Teamwork'], 'job_type': 'part_time', 'experience_level': 'entry', 'work_mode': 'onsite', 'location': 'Leeds, UK', 'salary_min': 22000, 'salary_max': 26000, 'category': 'Retail & E-commerce', 'company_idx': 8},
    {'title': 'Freelance Visual Merchandiser', 'description': 'Seasonal freelance to create compelling in-store displays and window installations for new collections.', 'requirements': 'Visual merchandising portfolio · Creative eye · Ability to work quickly and independently · Driving licence preferred', 'responsibilities': 'Design and build window displays · Create in-store installations · Brief and guide store teams', 'skills_required': ['Visual Merchandising', 'Retail Display', 'Creative Design', 'Store Layout', 'Brand Guidelines'], 'job_type': 'freelance', 'experience_level': 'mid', 'work_mode': 'onsite', 'location': 'Various UK Stores', 'salary_min': 180, 'salary_max': 280, 'category': 'Retail & E-commerce', 'company_idx': 8},
    {'title': 'Retail Tech Developer (Shopify)', 'description': 'Build and maintain our Shopify Plus e-commerce platform and internal retail technology integrations.', 'requirements': '2+ years Shopify development · Liquid templating · JavaScript · API integrations · Retail domain knowledge', 'responsibilities': 'Develop custom Shopify themes and apps · Integrate with POS and ERP · Maintain performance', 'skills_required': ['Shopify', 'Liquid', 'JavaScript', 'React', 'REST APIs', 'E-commerce', 'Node.js'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Leeds, UK', 'salary_min': 45000, 'salary_max': 60000, 'category': 'Software Engineering', 'company_idx': 8},
    # ── GRAND HOTELS GROUP (9) ───────────────────────────────────────────────
    {'title': 'Hotel General Manager', 'description': 'Lead the full operation of our flagship 150-room London property. Own P&L, guest experience, and team development.', 'requirements': '5+ years hotel management · Luxury hotel experience · Revenue management · Strong leadership', 'responsibilities': 'Lead hotel operations · Drive guest satisfaction scores · Own financial performance · Develop team', 'skills_required': ['Hotel Management', 'Revenue Management', 'P&L', 'Guest Experience', 'Team Leadership', 'Luxury Hospitality'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'onsite', 'location': 'London, UK', 'salary_min': 70000, 'salary_max': 90000, 'category': 'Hospitality & Tourism', 'company_idx': 9},
    {'title': 'Head Chef', 'description': 'Lead our brigade of 12 in our award-winning restaurant. Create seasonal menus, maintain quality standards, develop kitchen team.', 'requirements': '5+ years chef experience with 2+ years as head chef · Michelin or AA rosette background preferred · Menu development · Team leadership', 'responsibilities': 'Create seasonal menus · Lead and develop kitchen brigade · Manage food costs · Maintain hygiene standards', 'skills_required': ['Menu Development', 'Team Leadership', 'Food Cost Management', 'Fine Dining', 'HACCP', 'Culinary Arts'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'onsite', 'location': 'London, UK', 'salary_min': 55000, 'salary_max': 70000, 'category': 'Hospitality & Tourism', 'company_idx': 9},
    {'title': 'Revenue Manager', 'description': 'Maximise RevPAR across our 15 properties through pricing, distribution strategy, and demand forecasting.', 'requirements': '2+ years revenue management · Opera or equivalent PMS · OTA strategy · Strong analytical skills', 'responsibilities': 'Set pricing strategy · Manage OTA distribution · Forecast demand · Report to GM', 'skills_required': ['Revenue Management', 'Opera PMS', 'OTA Management', 'Pricing Strategy', 'Excel', 'Forecasting'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 42000, 'salary_max': 56000, 'category': 'Hospitality & Tourism', 'company_idx': 9},
    {'title': 'Front of House Supervisor', 'description': 'Supervise the guest-facing team at our Edinburgh property. Ensure every guest interaction reflects our luxury brand standards.', 'requirements': '2+ years hotel front of house · Supervisory experience · Exceptional guest service · OPERA knowledge', 'responsibilities': 'Supervise reception team · Handle guest feedback · Train new team members · Support duty manager', 'skills_required': ['Front of House', 'Guest Service', 'Opera PMS', 'Supervision', 'Complaint Handling', 'Upselling'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'onsite', 'location': 'Edinburgh, UK', 'salary_min': 28000, 'salary_max': 36000, 'category': 'Hospitality & Tourism', 'company_idx': 9},
    {'title': 'Events Coordinator (Part-time)', 'description': 'Coordinate private dining, weddings, and corporate events at our Manchester property. 3 days per week.', 'requirements': '1+ year events coordination · Organised and detail-oriented · Client-facing experience · Flexible on weekends', 'responsibilities': 'Coordinate event logistics · Liaise with clients and suppliers · Support events on the day', 'skills_required': ['Event Planning', 'Client Liaison', 'Events Coordination', 'Communication', 'Organisation', 'Hospitality'], 'job_type': 'part_time', 'experience_level': 'entry', 'work_mode': 'onsite', 'location': 'Manchester, UK', 'salary_min': 23000, 'salary_max': 29000, 'category': 'Hospitality & Tourism', 'company_idx': 9},
    {'title': 'Hospitality Intern (Summer)', 'description': '10-week paid internship rotating across front desk, food and beverage, and events departments.', 'requirements': 'Studying hospitality, tourism, or business · Friendly and professional · Willing to work shifts · Passion for hospitality', 'responsibilities': 'Rotate across hotel departments · Assist with guest service · Support events delivery', 'skills_required': ['Customer Service', 'Communication', 'Teamwork', 'Hospitality', 'Adaptability'], 'job_type': 'internship', 'experience_level': 'entry', 'work_mode': 'onsite', 'location': 'London, UK', 'salary_min': 20000, 'salary_max': 23000, 'category': 'Hospitality & Tourism', 'company_idx': 9},
    {'title': 'Freelance Wedding Photographer', 'description': 'Document weddings and events at our hotel venues. We work with a roster of photographers for bookings throughout the year.', 'requirements': 'Professional photography portfolio · Wedding and events experience · Own professional equipment · Editing skills (Lightroom/Capture One)', 'responsibilities': 'Photograph wedding ceremonies and receptions · Deliver edited galleries on time · Coordinate with couples and hotel team', 'skills_required': ['Photography', 'Wedding Photography', 'Lightroom', 'Capture One', 'Editing', 'Client Communication'], 'job_type': 'freelance', 'experience_level': 'mid', 'work_mode': 'onsite', 'location': 'Various UK Hotels', 'salary_min': 800, 'salary_max': 2000, 'category': 'Hospitality & Tourism', 'company_idx': 9},
    # ── LAWBRIDGE LLP (10) ───────────────────────────────────────────────────
    {'title': 'Commercial Solicitor (3–5 PQE)', 'description': 'Join our leading commercial team advising clients on M&A, joint ventures, and commercial contracts. Excellent career progression to partnership.', 'requirements': '3–5 years PQE in commercial law · Corporate/M&A experience · Strong drafting skills · Business development interest', 'responsibilities': 'Advise on commercial contracts and transactions · Draft and negotiate agreements · Support senior partners on complex deals', 'skills_required': ['Commercial Law', 'Contract Drafting', 'M&A', 'Corporate Law', 'Negotiation', 'Client Management'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 80000, 'salary_max': 110000, 'category': 'Legal Services', 'company_idx': 10},
    {'title': 'Employment Law Associate', 'description': 'Advise employer and employee clients on a full range of employment law matters from contracts to tribunal claims.', 'requirements': '2+ years PQE in employment law · Tribunal advocacy experience · Strong client skills', 'responsibilities': 'Advise on employment contracts and disputes · Represent clients at tribunal · Draft settlement agreements', 'skills_required': ['Employment Law', 'Tribunal Advocacy', 'Contract Drafting', 'HR Advisory', 'Legal Research'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Manchester, UK', 'salary_min': 65000, 'salary_max': 85000, 'category': 'Legal Services', 'company_idx': 10},
    {'title': 'Legal Secretary (Part-time)', 'description': 'Support our corporate department with document management, client correspondence, and diary management. 3 days per week.', 'requirements': 'Legal secretarial experience · Excellent typing and attention to detail · MS Office · Professional communication', 'responsibilities': 'Prepare and format legal documents · Manage partner diaries · Handle client correspondence', 'skills_required': ['Legal Secretary', 'Document Management', 'MS Office', 'Attention to Detail', 'Client Communication'], 'job_type': 'part_time', 'experience_level': 'mid', 'work_mode': 'onsite', 'location': 'London, UK', 'salary_min': 25000, 'salary_max': 33000, 'category': 'Legal Services', 'company_idx': 10},
    {'title': 'Trainee Solicitor (2-Year Contract)', 'description': 'Structured 2-year training contract rotating through corporate, litigation, employment, and real estate departments.', 'requirements': 'LPC completed or SQE passed · Strong academics (2:1 minimum) · Commercial awareness · Resilient and proactive', 'responsibilities': 'Rotate through practice areas · Assist on live client matters · Develop legal skills under supervision', 'skills_required': ['Legal Research', 'Drafting', 'Client Service', 'Commercial Awareness', 'Problem Solving'], 'job_type': 'contract', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 45000, 'salary_max': 55000, 'category': 'Legal Services', 'company_idx': 10},
    {'title': 'Freelance Legal Translator (French/English)', 'description': 'Translate legal documents, contracts, and correspondence between French and English. Project-based, remote.', 'requirements': 'Native-level French and English · Legal translation experience · Attention to legal terminology · Confidentiality standards', 'responsibilities': 'Translate contracts and legal documents · Proofread translations · Meet deadlines for client transactions', 'skills_required': ['Legal Translation', 'French', 'English', 'Contract Law', 'Attention to Detail'], 'job_type': 'freelance', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote', 'salary_min': 60, 'salary_max': 120, 'category': 'Legal Services', 'company_idx': 10},
    # ── DESIGNSPACE ARCHITECTS (11) ─────────────────────────────────────────
    {'title': 'Architect (Part II / ARB Registered)', 'description': 'Work on award-winning residential and commercial projects from concept through planning to construction.', 'requirements': 'ARB registered or Part II qualified · Portfolio of built projects · Revit/AutoCAD/Rhino · Sustainable design knowledge', 'responsibilities': 'Lead project design from concept to delivery · Produce planning applications · Collaborate with engineers and contractors', 'skills_required': ['Architecture', 'Revit', 'AutoCAD', 'Rhino', 'Sustainable Design', 'Planning Applications', 'BIM'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 40000, 'salary_max': 56000, 'category': 'Architecture & Construction', 'company_idx': 11},
    {'title': 'BIM Manager', 'description': 'Lead Building Information Modelling strategy across all DesignSpace projects. Set standards, train team, manage model quality.', 'requirements': '4+ years BIM management · Revit expert · BIM360 or Autodesk Construction Cloud · ISO 19650 knowledge', 'responsibilities': 'Set BIM standards and workflows · Manage model quality and coordination · Train project teams · Liaise with contractors', 'skills_required': ['BIM Management', 'Revit', 'Navisworks', 'BIM360', 'ISO 19650', 'AutoCAD', 'Coordination'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 58000, 'salary_max': 72000, 'category': 'Architecture & Construction', 'company_idx': 11},
    {'title': 'Architectural Visualiser', 'description': 'Create compelling CGI renders, animations, and interactive visualisations for client presentations and planning applications.', 'requirements': '2+ years architectural visualisation · 3ds Max, Lumion, or Enscape · Photoshop for post-production · Architectural context understanding', 'responsibilities': 'Produce photorealistic renders · Create walkthrough animations · Support planning and client presentations', 'skills_required': ['Architectural Visualisation', '3ds Max', 'Lumion', 'Enscape', 'Photoshop', 'CGI', 'V-Ray'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 36000, 'salary_max': 48000, 'category': 'Architecture & Construction', 'company_idx': 11},
    {'title': 'Freelance Planning Consultant', 'description': 'Advise on planning applications and appeals for residential and commercial development projects. Project-based engagement.', 'requirements': 'MRTPI qualified or pursuing · Planning application experience · Appeals experience a plus · Strong report writing', 'responsibilities': 'Prepare and submit planning applications · Write planning statements · Support planning appeals', 'skills_required': ['Town Planning', 'Planning Applications', 'MRTPI', 'Report Writing', 'Development Management'], 'job_type': 'freelance', 'experience_level': 'senior', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 500, 'salary_max': 700, 'category': 'Architecture & Construction', 'company_idx': 11},
    {'title': 'Architecture Part I Assistant', 'description': 'First professional experience for a Part I architecture graduate. Work on live projects in a supportive studio environment.', 'requirements': 'Part I architecture qualification · Revit or AutoCAD · Portfolio demonstrating design ability · Enthusiastic and eager to learn', 'responsibilities': 'Support design team on live projects · Produce drawings and models · Assist with client presentations', 'skills_required': ['Architecture', 'Revit', 'AutoCAD', 'SketchUp', 'Photoshop', 'InDesign', 'Design'], 'job_type': 'full_time', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 26000, 'salary_max': 33000, 'category': 'Architecture & Construction', 'company_idx': 11},
    # ── NORTHSTAR MEDIA (12) ─────────────────────────────────────────────────
    {'title': 'Investigative Journalist', 'description': 'Lead long-form investigative journalism projects on politics, corporate accountability, and social issues.', 'requirements': '3+ years investigative journalism · NCTJ or equivalent qualification · Experience with FOI requests · Strong source development', 'responsibilities': 'Lead investigative projects · Conduct research and interviews · Write long-form articles · Collaborate with editors', 'skills_required': ['Investigative Journalism', 'FOI Requests', 'Interviewing', 'Long-form Writing', 'Research', 'NCTJ'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'Glasgow, UK', 'salary_min': 36000, 'salary_max': 48000, 'category': 'Media & Journalism', 'company_idx': 12},
    {'title': 'Documentary Producer', 'description': 'Develop and produce documentary content for streaming platforms and broadcast. Own projects from pitch to delivery.', 'requirements': '4+ years documentary production · Shooting and directing experience · Knowledge of commissioning landscape · Strong storytelling', 'responsibilities': 'Develop documentary ideas · Pitch to commissioners · Manage production budgets · Oversee post-production', 'skills_required': ['Documentary Production', 'Directing', 'Pitching', 'Budget Management', 'Storytelling', 'Commissioning'], 'job_type': 'full_time', 'experience_level': 'senior', 'work_mode': 'hybrid', 'location': 'Glasgow, UK', 'salary_min': 48000, 'salary_max': 65000, 'category': 'Media & Journalism', 'company_idx': 12},
    {'title': 'Podcast Producer', 'description': 'Produce, edit, and grow our award-winning investigative podcast. Own the editorial calendar and guest bookings.', 'requirements': '2+ years podcast production · Audio editing (Audition or Logic) · Strong editorial judgement · Social media growth', 'responsibilities': 'Produce and edit weekly episodes · Book and brief guests · Grow audience across platforms', 'skills_required': ['Podcast Production', 'Audio Editing', 'Adobe Audition', 'Editorial Judgement', 'Guest Booking', 'Social Growth'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote (UK)', 'salary_min': 34000, 'salary_max': 44000, 'category': 'Media & Journalism', 'company_idx': 12},
    {'title': 'Freelance Videographer', 'description': 'Shoot documentary-style footage for our news and investigative content. Project-based, UK-based required.', 'requirements': 'Videography portfolio · Documentary shooting style · Sony FS7 or similar · Self-shooting experience', 'responsibilities': 'Shoot interviews and observational footage · Operate independently · Deliver to broadcast spec', 'skills_required': ['Videography', 'Documentary', 'Sony FS7', 'Self-shooting', 'Lighting', 'Location Sound'], 'job_type': 'freelance', 'experience_level': 'mid', 'work_mode': 'onsite', 'location': 'Various UK Locations', 'salary_min': 350, 'salary_max': 600, 'category': 'Media & Journalism', 'company_idx': 12},
    {'title': 'Junior Reporter (Trainee)', 'description': 'Your first newsroom role. Learn investigative journalism from experienced reporters and start building your own stories.', 'requirements': 'Journalism degree or NCTJ · Strong writing · Digital-first mindset · Relentless curiosity', 'responsibilities': 'Research and write news stories · Assist senior journalists · Build source networks · Write for web and social', 'skills_required': ['News Writing', 'Research', 'Digital Journalism', 'Social Media', 'NCTJ', 'Interviewing'], 'job_type': 'full_time', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'Glasgow, UK', 'salary_min': 24000, 'salary_max': 30000, 'category': 'Media & Journalism', 'company_idx': 12},
    {'title': 'Data Journalist (Part-time)', 'description': 'Turn complex data into compelling stories. 2–3 days per week, flexible for someone balancing freelance work.', 'requirements': 'Journalism background with data skills · Python or R · Data visualisation (Flourish, Datawrapper) · Ability to explain complex data simply', 'responsibilities': 'Analyse public datasets · Create data visualisations · Write data-driven stories · Fact-check statistical claims', 'skills_required': ['Data Journalism', 'Python', 'R', 'Flourish', 'Datawrapper', 'Statistical Analysis', 'Storytelling'], 'job_type': 'part_time', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote (UK)', 'salary_min': 28000, 'salary_max': 38000, 'category': 'Media & Journalism', 'company_idx': 12},
    # ── HOPE FOUNDATION (13) ────────────────────────────────────────────────
    {'title': 'Youth Mental Health Practitioner', 'description': 'Provide therapeutic support to young people aged 11–25 experiencing anxiety, depression, and trauma. Deliver both one-to-one and group programmes.', 'requirements': 'Qualified counsellor or therapist (BACP or UKCP registered) · Experience working with young people · Knowledge of safeguarding · Genuine passion for mental health', 'responsibilities': 'Deliver therapeutic interventions · Maintain case notes and clinical records · Participate in clinical supervision · Contribute to service development', 'skills_required': ['Counselling', 'CBT', 'Youth Work', 'Safeguarding', 'BACP', 'Mental Health', 'Case Management'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'onsite', 'location': 'London, UK', 'salary_min': 32000, 'salary_max': 42000, 'category': 'Charity & Non-profit', 'company_idx': 13},
    {'title': 'Fundraising Manager', 'description': 'Lead individual giving, corporate partnerships, and grant fundraising. Own and grow a £500k income stream.', 'requirements': '3+ years charity fundraising · Individual giving and major donor experience · Bid writing skills · CRM (Salesforce or Raiser\'s Edge)', 'responsibilities': 'Manage individual giving programme · Cultivate major donors · Write grant applications · Report to Director of Fundraising', 'skills_required': ['Fundraising', 'Major Donor', 'Grant Writing', 'Salesforce', 'Individual Giving', 'Corporate Partnerships'], 'job_type': 'full_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 38000, 'salary_max': 50000, 'category': 'Charity & Non-profit', 'company_idx': 13},
    {'title': 'Community Outreach Coordinator', 'description': 'Build relationships with schools, community organisations, and local authorities to reach young people who need our services.', 'requirements': '2+ years community work or youth work · Strong relationship-building skills · Knowledge of youth mental health · Full driving licence', 'responsibilities': 'Build referral partnerships · Deliver awareness sessions in schools · Represent Hope Foundation at community events', 'skills_required': ['Community Outreach', 'Youth Work', 'Partnership Building', 'Presentation', 'Mental Health Awareness'], 'job_type': 'full_time', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 27000, 'salary_max': 34000, 'category': 'Charity & Non-profit', 'company_idx': 13},
    {'title': 'Volunteer Coordinator (Part-time)', 'description': 'Recruit, train, and support 150+ volunteers who deliver our community mental health programmes. 3 days per week.', 'requirements': 'Volunteer management experience · Organised and supportive · Safeguarding knowledge · DBS required', 'responsibilities': 'Recruit and onboard volunteers · Deliver volunteer training · Provide ongoing support · Recognise and retain volunteers', 'skills_required': ['Volunteer Management', 'Recruitment', 'Training', 'Safeguarding', 'Organisation', 'Communication'], 'job_type': 'part_time', 'experience_level': 'mid', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 24000, 'salary_max': 30000, 'category': 'Charity & Non-profit', 'company_idx': 13},
    {'title': 'Digital Communications Officer', 'description': 'Grow our digital presence to reach more young people and supporters. Own social media, email, and website content.', 'requirements': '2+ years digital communications · Social media management · Email marketing · Website CMS (WordPress) · Charity or public sector experience a plus', 'responsibilities': 'Manage social media channels · Write email newsletters · Update website content · Track and report engagement metrics', 'skills_required': ['Social Media', 'Email Marketing', 'WordPress', 'Copywriting', 'Analytics', 'Digital Communications'], 'job_type': 'full_time', 'experience_level': 'entry', 'work_mode': 'hybrid', 'location': 'London, UK', 'salary_min': 26000, 'salary_max': 34000, 'category': 'Charity & Non-profit', 'company_idx': 13},
    {'title': 'Freelance Grant Writer', 'description': 'Research and write grant applications to trusts, foundations, and statutory funders. Project-based, remote.', 'requirements': 'Proven grant writing track record · Charity sector experience · Excellent research and writing skills · Can work to tight deadlines', 'responsibilities': 'Research funding opportunities · Write compelling grant applications · Report on successful grants · Support bid reviews', 'skills_required': ['Grant Writing', 'Bid Writing', 'Charity Fundraising', 'Research', 'Copywriting', 'Trust Fundraising'], 'job_type': 'freelance', 'experience_level': 'mid', 'work_mode': 'remote', 'location': 'Remote', 'salary_min': 250, 'salary_max': 450, 'category': 'Charity & Non-profit', 'company_idx': 13},
    {'title': 'Therapy Intern (Post-Graduate Placement)', 'description': 'Accredited post-graduate placement for trainee therapists. Supervised caseload, clinical training, and professional development.', 'requirements': 'Enrolled on accredited counselling/therapy training · Student BACP membership · Available 2 days/week · Commitment to safeguarding', 'responsibilities': 'Carry a supervised caseload of 6–8 young people · Attend weekly group supervision · Complete clinical placement hours', 'skills_required': ['Counselling', 'Person-centred Therapy', 'Safeguarding', 'Case Notes', 'Supervision', 'Mental Health'], 'job_type': 'internship', 'experience_level': 'entry', 'work_mode': 'onsite', 'location': 'London, UK', 'salary_min': 15000, 'salary_max': 20000, 'category': 'Charity & Non-profit', 'company_idx': 13},
]

SAMPLE_APPLICATIONS = [
    {'candidate_idx': 0, 'job_title': 'Senior Full-Stack Developer',  'status': 'shortlisted', 'cover': 'I have 5 years building Django + React applications and would love to bring that to TechCorp.'},
    {'candidate_idx': 0, 'job_title': 'Backend Python Developer',     'status': 'reviewing',   'cover': 'Python and Django REST Framework are my core stack. I write tests first and care deeply about API design.'},
    {'candidate_idx': 0, 'job_title': 'Freelance React Developer',    'status': 'pending',     'cover': 'Available for 3 months. React and TypeScript are my daily tools. Happy to provide references.'},
    {'candidate_idx': 1, 'job_title': 'Data Scientist',               'status': 'interview',   'cover': 'My MSc focused on NLP and I have production experience with scikit-learn pipelines — this role is a perfect fit.'},
    {'candidate_idx': 1, 'job_title': 'NLP Research Engineer',        'status': 'pending',     'cover': 'I specialise in NLP and have worked extensively with HuggingFace Transformers for classification and NER.'},
    {'candidate_idx': 1, 'job_title': 'AI / ML Engineer — Personalised Learning', 'status': 'reviewing', 'cover': 'Keen to apply ML skills in an EdTech context where the social impact is tangible.'},
    {'candidate_idx': 2, 'job_title': 'DevOps / Platform Engineer',   'status': 'offered',     'cover': 'AWS Certified Solutions Architect with 4 years of Kubernetes experience at scale.'},
    {'candidate_idx': 2, 'job_title': 'Software Engineer — Energy Grid', 'status': 'reviewing', 'cover': 'Excited about clean energy. My Python and infrastructure skills translate directly to IoT grid systems.'},
    {'candidate_idx': 2, 'job_title': 'Retail Tech Developer (Shopify)', 'status': 'shortlisted', 'cover': 'Strong JavaScript and API integration experience. Keen to work on high-traffic e-commerce systems.'},
]


class Command(BaseCommand):
    help = (
        'Seeds 108 diverse jobs across 14 companies covering Tech, Data, Healthcare, Finance,\n'
        'Creative, EdTech, Gaming, Clean Energy, Retail, Hospitality, Legal, Architecture,\n'
        'Media, and Charity sectors.\n\n'
        'All job types: full_time, part_time, contract, freelance, internship\n'
        'All work modes: onsite, remote, hybrid\n'
        'All experience levels: entry, mid, senior, lead, executive'
    )

    def add_arguments(self, parser):
        parser.add_argument('--clear', action='store_true', help='Delete existing seed data first.')

    def handle(self, *args, **options):
        from accounts.models import User, CandidateProfile, RecruiterProfile
        from applications.models import Application, ApplicationStatusHistory
        from jobs.models import Job

        if options['clear']:
            self.stdout.write('🗑  Clearing existing seed data...')
            emails = [r['email'] for r in RECRUITERS] + [c['email'] for c in CANDIDATES]
            Application.objects.filter(candidate__email__in=emails).delete()
            Job.objects.filter(recruiter__email__in=emails).delete()
            User.objects.filter(email__in=emails).delete()
            self.stdout.write(self.style.SUCCESS('   Done.\n'))

        with transaction.atomic():
            # ── Recruiters ────────────────────────────────────────────────────
            recruiter_users = []
            for rec in RECRUITERS:
                user, created = User.objects.get_or_create(
                    email=rec['email'],
                    defaults={'full_name': rec['full_name'], 'role': User.RECRUITER}
                )
                if created:
                    user.set_password(rec['password'])
                    user.is_email_verified = True
                    user.save()
                    RecruiterProfile.objects.create(user=user, **rec['company'])
                    self.stdout.write(self.style.SUCCESS(f'  ✓ Recruiter  {user.full_name:<28} → {rec["company"]["company_name"]}'))
                else:
                    self.stdout.write(f'  → Exists  {user.email}')
                recruiter_users.append(user)

            self.stdout.write('')

            # ── Candidates ────────────────────────────────────────────────────
            candidate_users = []
            for cand in CANDIDATES:
                user, created = User.objects.get_or_create(
                    email=cand['email'],
                    defaults={'full_name': cand['full_name'], 'role': User.CANDIDATE}
                )
                if created:
                    user.set_password(cand['password'])
                    user.is_email_verified = True
                    user.save()
                    CandidateProfile.objects.create(user=user, **cand['profile'])
                    self.stdout.write(self.style.SUCCESS(f'  ✓ Candidate  {user.full_name}'))
                else:
                    self.stdout.write(f'  → Exists  {user.email}')
                candidate_users.append(user)

            self.stdout.write('')

            # ── Jobs ──────────────────────────────────────────────────────────
            job_map: dict[str, 'Job'] = {}
            jobs_created = 0
            for job_data in JOBS:
                recruiter = recruiter_users[job_data.pop('company_idx')]
                company_name = recruiter.recruiter_profile.company_name
                job, created = Job.objects.get_or_create(
                    title=job_data['title'],
                    recruiter=recruiter,
                    defaults={**job_data, 'company_name': company_name},
                )
                job_map[job.title] = job
                if created:
                    jobs_created += 1

            self.stdout.write(self.style.SUCCESS(
                f'  ✓ {jobs_created} jobs created  ({len(JOBS) - jobs_created} already existed)'
            ))

            # ── Applications ──────────────────────────────────────────────────
            apps_created = 0
            for app_data in SAMPLE_APPLICATIONS:
                candidate = candidate_users[app_data['candidate_idx']]
                job = job_map.get(app_data['job_title'])
                if not job:
                    continue
                app, created = Application.objects.get_or_create(
                    job=job, candidate=candidate,
                    defaults={'status': app_data['status'], 'cover_letter': app_data['cover']}
                )
                if created:
                    ApplicationStatusHistory.objects.create(
                        application=app, from_status='', to_status=Application.PENDING,
                        note='Application submitted', changed_by=candidate,
                    )
                    if app_data['status'] != Application.PENDING:
                        ApplicationStatusHistory.objects.create(
                            application=app, from_status=Application.PENDING,
                            to_status=app_data['status'], note='Status updated by recruiter',
                            changed_by=job.recruiter,
                        )
                    apps_created += 1

            self.stdout.write(self.style.SUCCESS(f'  ✓ {apps_created} applications created'))

        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS('✅  Seed complete!'))
        self.stdout.write('')
        self.stdout.write(f'  {len(JOBS)} jobs  ·  14 companies  ·  8 sectors')
        self.stdout.write('')
        self.stdout.write('  Recruiter logins (password: BytesJobs#26):')
        for r in RECRUITERS:
            self.stdout.write(f'    {r["email"]:<42} → {r["company"]["company_name"]}')
        self.stdout.write('')
        self.stdout.write('  Candidate logins (password: BytesJobs#26):')
        for c in CANDIDATES:
            self.stdout.write(f'    {c["email"]}')
        self.stdout.write('')
