# Generated by Django 4.2.13 on 2026-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds the Hired / Offer Declined pipeline statuses, and creates three
    indexes (app_candidate_status_idx, app_job_status_idx, app_job_score_idx)
    that were already declared in Application.Meta.indexes but had never
    actually been migrated -- a pre-existing gap from before this change,
    closed here.
    """

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('offered', 'Offer Extended'), ('hired', 'Hired'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', 'status'], name='app_candidate_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='app_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', '-match_score'], name='app_job_score_idx'),
        ),
    ]
