# Generated by Django 4.2.13 on 2026-07-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_hired_offer_declined_status_and_missing_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('round_type', models.CharField(choices=[('screen', 'Phone/Video Screen'), ('technical', 'Technical Interview'), ('onsite', 'Onsite'), ('final', 'Final Round'), ('other', 'Other')], default='screen', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=150)),
                ('feedback', models.TextField(blank=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='1-5 scorecard rating, recruiter-private.', null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='applications.application')),
            ],
            options={
                'db_table': 'interview_rounds',
                'ordering': ['round_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='interviewround',
            # See the matching suppression comment on this constraint's
            # definition in applications/models.py -- `check=` is correct
            # for Django 4.2.13; the type-checker error is a
            # djangorestframework-stubs/django-stubs version-pairing
            # limitation, not a real bug.
            constraint=models.CheckConstraint(check=models.Q(models.Q(('score__gte', 1), ('score__lte', 5)), ('score__isnull', True), _connector='OR'), name='interview_round_score_range'),  # pyright: ignore[reportCallIssue]
        ),
        migrations.AlterUniqueTogether(
            name='interviewround',
            unique_together={('application', 'round_number')},
        ),
    ]
